### ISSUE TITLE
Hain v0.6.2 - hain.exe electron process persistent CPU spike

### ISSUE THREAD

**Issue by jump** [hainproject/hain#229] opened 2017-03-25 13:30 UTC
on my machine one of the hain threads is really consuming CPU usage. 
(i5-2500k @ 4.5GHz, 16GB RAM) 

It spikes from idle, to up to 50%, and will stick around there between 30-50% when doing nothing. this is weeks after indexing has completed. 

Please let me know how to generate debug information on this so I can help to improve hain

**Comment by cpriest** [comment] 2017-03-27 19:46
By default, hain-plugin-filesearch re-indexes every 5 minutes I believe, 
if you have some directories set to be recursive, this could be the cause.

In the same directory as hain.exe you'll find a hain-debug.log which 
would show such activity.

**Comment by shaivyamahajan** [comment] 2017-04-23 15:39
wonder if this can be improved by storing last modified dates on recursive trees

**Comment by cpriest** [comment] 2017-04-23 17:36
I'd want to get confirmation that is the cause.  The best way to do this would be to run hain from a command shell (cmd.exe) which will show the output of what it's doing.  See what is being logged when the spike happens.  I haven't personally noticed any spikes while having it running.

**Comment by cpriest** [comment] 2017-05-02 22:14
Closing this as OP has not responded.

**Closed by cpriest** 2017-05-02 22:14 UTC

**Comment by jump** [comment] 2017-06-26 13:18
sorry, I forgot to update this issue. I am no longer seeing this issue in the latest versions. 0.6.4
